<script setup lang="ts">
import {computed,nextTick,onMounted,onUnmounted,ref,watch} from 'vue';
import {catalog} from './catalog';
import {TYPES,STATUSES,EMPTY,addItem,updateEntry,validateItem,validateLibrary,searchItems,releaseState,localToday,calendarExport} from './library';
import type {MediaItem,Library,Status,MediaType} from './library';
const STORAGE='mediamemo-library-v1';
const message=ref(''),storageError=ref(false),query=ref(''),type=ref('all'),statusFilter=ref('all'),sort=ref('recent');
const view=ref(['discover','shelf','calendar'].includes(location.hash.slice(1))?location.hash.slice(1):'discover');
const library=ref<Library>({...EMPTY,entries:[]});
const recoveryCopy=ref<string|null>(null);
try{const data=localStorage.getItem(STORAGE);if(data){try{library.value=validateLibrary(JSON.parse(data));}catch{recoveryCopy.value=data;message.value='Saved data needs recovery. Export its original copy before importing a repaired library. New changes stay in memory.';storageError.value=true;}}}catch{message.value='Browser storage is unavailable. Export your changes to keep them.';storageError.value=true;}
function persist(){if(recoveryCopy.value!==null){storageError.value=true;message.value='Recovery mode: original saved data is protected. Export it before importing a repaired library.';return;}try{localStorage.setItem(STORAGE,JSON.stringify(library.value));storageError.value=false;}catch{storageError.value=true;message.value='Browser storage is unavailable or full. Export your library to keep this session’s changes.';}}
function navigate(next:string){view.value=next;location.hash=next;query.value='';statusFilter.value='all';message.value='';}
function hashChange(){const hash=location.hash.slice(1);if(['discover','shelf','calendar'].includes(hash))view.value=hash;}
onMounted(()=>window.addEventListener('hashchange',hashChange));onUnmounted(()=>window.removeEventListener('hashchange',hashChange));
const today=ref(localToday());
let clock:ReturnType<typeof setInterval>;
onMounted(()=>{clock=setInterval(()=>today.value=localToday(),60000);});onUnmounted(()=>clearInterval(clock));
const typeLabels:Record<MediaType,string>={film:'Film',game:'Game',series:'Series',music:'Music',book:'Book'};
const statusLabels:Record<Status,string>={planned:'On the list',active:'In progress',completed:'Finished',paused:'On pause',dropped:'Set aside'};
const counts=computed(()=>({all:library.value.entries.length,active:library.value.entries.filter(e=>e.status==='active').length,finished:library.value.entries.filter(e=>e.status==='completed').length,upcoming:library.value.entries.filter(e=>releaseState(e.item.releaseDate,today.value)==='upcoming').length}));
const discoverItems=computed(()=>searchItems(catalog,query.value,type.value));
const shelfItems=computed(()=>{
 const matching=new Set(searchItems(library.value.entries.map(e=>e.item),query.value,type.value).map(i=>i.id));
 return library.value.entries.filter(e=>matching.has(e.item.id)&&(statusFilter.value==='all'||statusFilter.value==='favorites'?statusFilter.value!=='favorites'||e.favorite:e.status===statusFilter.value)).sort((a,b)=>sort.value==='title'?a.item.title.localeCompare(b.item.title):sort.value==='rating'?b.rating-a.rating:sort.value==='release'?(a.item.releaseDate||'9999').localeCompare(b.item.releaseDate||'9999'):b.addedAt.localeCompare(a.addedAt));
});
const calendarGroups=computed(()=>{
 const groups:Record<string,typeof library.value.entries>={};
 for(const entry of shelfItems.value){const state=releaseState(entry.item.releaseDate,today.value);const key=state==='unknown'?'Date to be announced':state==='released'?'Already released':entry.item.releaseDate.slice(0,7);(groups[key]??=[]).push(entry);}
 return Object.entries(groups).sort(([a],[b])=>{const weight=(s:string)=>s==='Already released'?'9998':s==='Date to be announced'?'9999':s;return weight(a).localeCompare(weight(b));}).map(([name,entries])=>({name,entries:entries.sort((a,b)=>a.item.releaseDate.localeCompare(b.item.releaseDate))}));
});
const selected=ref<MediaItem|null>(null),detailDialog=ref<HTMLDialogElement|null>(null),editDialog=ref<HTMLDialogElement|null>(null),importInput=ref<HTMLInputElement|null>(null);
const selectedEntry=computed(()=>library.value.entries.find(e=>e.item.id===selected.value?.id));
const draftNotes=ref('');
async function openItem(item:MediaItem){selected.value=library.value.entries.find(e=>e.item.id===item.id)?.item||item;draftNotes.value=selectedEntry.value?.notes||'';await nextTick();detailDialog.value?.showModal();}
function entryFor(id:string){return library.value.entries.find(e=>e.item.id===id);}
function add(item:MediaItem){try{const exists=!!entryFor(item.id);library.value=addItem(library.value,item);persist();message.value=exists?'Already on your shelf.':`${item.title} added to your shelf.`;}catch(error){message.value=(error as Error).message;}}
function update(id:string,changes:Parameters<typeof updateEntry>[2]){try{library.value=updateEntry(library.value,id,changes);persist();message.value='Your shelf is up to date.';}catch(error){message.value=(error as Error).message;}}
function remove(id:string){const entry=entryFor(id);if(!entry||!confirm(`Remove “${entry.item.title}” and its notes from this shelf?`))return;library.value={...library.value,entries:library.value.entries.filter(e=>e.item.id!==id)};persist();detailDialog.value?.close();message.value='Removed from your shelf.';}
function formatDate(date:string){return date?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(date+'T12:00:00')):'Date not announced';}
function monthLabel(value:string){return /^\d{4}-\d{2}$/.test(value)?new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(value+'-15T12:00:00')):value;}
function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportLibrary(){if(recoveryCopy.value!==null){download('mediamemo-recovery.json',recoveryCopy.value);message.value='Original saved data exported for recovery.';return;}download('mediamemo-library.json',JSON.stringify(library.value));message.value='Library exported with titles, status, ratings, and notes.';}
function exportCalendar(){const dated=library.value.entries.filter(e=>e.item.releaseDate);if(!dated.length){message.value='Add a release date to at least one saved item first.';return;}download('mediamemo-releases.ics',calendarExport(dated),'text/calendar');message.value='Calendar exported. Import it into your calendar app; this is a snapshot, not a subscription.';}
async function importLibrary(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw new Error('Choose a library file smaller than 5 MB.');const imported=validateLibrary(JSON.parse(await file.text()));if((library.value.entries.length||recoveryCopy.value!==null)&&!confirm('Replace your current shelf with this library? Export first to keep a backup.'))return;recoveryCopy.value=null;library.value=imported;persist();navigate('shelf');message.value=`Imported ${imported.entries.length} items.`;}catch(error){message.value='Import failed: '+(error as Error).message;}finally{input.value='';}}
const editId=ref<string|null>(null),formError=ref('');
const blankForm=()=>({title:'',type:'film' as MediaType,creator:'',releaseDate:'',description:'',genres:'',source:''});
const form=ref(blankForm());
async function editItem(item?:MediaItem){editId.value=item?.id||null;form.value=item?{...item,genres:item.genres.join(', ')}:blankForm();formError.value='';detailDialog.value?.close();await nextTick();editDialog.value?.showModal();}
function saveItem(){try{const old=editId.value?entryFor(editId.value):null;const item=validateItem({...form.value,id:editId.value||crypto.randomUUID(),genres:form.value.genres.split(',').map(g=>g.trim()).filter(Boolean),palette:old?.item.palette??library.value.entries.length%8,custom:true});
 const duplicate=library.value.entries.find(e=>e.item.id!==item.id&&e.item.title.toLowerCase()===item.title.toLowerCase()&&e.item.type===item.type);if(duplicate)throw new Error('That title and media type are already on your shelf.');
 library.value=editId.value?updateEntry(library.value,item.id,{item}):addItem(library.value,item);persist();editDialog.value?.close();navigate('shelf');message.value=editId.value?'Item updated.':'Your own addition, saved.';
}catch(error){formError.value=(error as Error).message;}}
function demoShelf(){if(library.value.entries.length){message.value='The demo shelf is available when your shelf is empty, so it never overwrites your work.';return;}let demo:Library={version:1,entries:[]};for(const item of catalog.slice(0,4))demo=addItem(demo,item);demo=updateEntry(demo,catalog[1].id,{status:'active'});demo=updateEntry(demo,catalog[2].id,{status:'completed',rating:4,notes:'Demo note: a place for the ideas that stay with you. Replace this with your own thoughts.'});library.value=demo;persist();navigate('shelf');message.value='Sample shelf loaded. These example statuses and notes are yours to edit.';}
watch(view,()=>{type.value='all';});
</script>

<template>
 <a class="skip" href="#content">Skip to collection</a>
 <div class="app-shell">
  <aside class="sidebar"><a class="logo" href="#discover" @click.prevent="navigate('discover')"><span class="logo-mark">m<span>m</span></span><span>MediaMEMO<small>KEEP A LITTLE CULTURE CLOSE.</small></span></a>
   <p class="nav-caption">YOUR SPACE</p><nav aria-label="Main"><button :class="{active:view==='discover'}" @click="navigate('discover')"><span>◈</span> Discover <i>↗</i></button><button :class="{active:view==='shelf'}" @click="navigate('shelf')"><span>▤</span> My shelf <b>{{ counts.all }}</b></button><button :class="{active:view==='calendar'}" @click="navigate('calendar')"><span>▦</span> Release calendar</button></nav>
   <div class="sidebar-note"><span>A SMALL REMINDER</span><p>Your taste is a story.<br>Give it somewhere to live.</p><a href="https://michaelsanders08.github.io/">Back to the utility desk ↗</a></div>
   <div class="storage-state"><i :class="{warning:storageError}"></i>{{ storageError?'Export to keep changes':'Saved in this browser' }}</div>
  </aside>
  <div class="main-shell"><header><span class="breadcrumb">YOUR CULTURE, COLLECTED <span>/</span> {{ view==='discover'?'Discover':view==='shelf'?'My shelf':'Release calendar' }}</span><div class="header-actions"><button class="text-button" @click="exportLibrary">Export</button><button class="text-button" @click="importInput?.click()">Import</button><input ref="importInput" class="sr-only" type="file" accept=".json,application/json" aria-label="Import library" @change="importLibrary"><button class="primary" @click="editItem()">+ Add your own</button></div></header>
  <main id="content">
   <section v-if="view==='discover'" class="hero"><div><p class="eyebrow">FOR THE VIEWERS. THE PLAYERS. THE CURIOUS.</p><h1>Make time for<br><em>good stories.</em></h1><p class="hero-copy">The things you want to watch, play, read, and hear.<br>A little less scattered. A little more yours.</p><div class="hero-actions"><button class="primary" @click="navigate('shelf')">Find your next thing <span>↗</span></button><button v-if="!counts.all" class="text-button" @click="demoShelf">Try a sample shelf</button></div></div><div class="hero-art" aria-hidden="true"><div class="mini-cover cover-back"><span>THE<br>WORLDS<br>WE MAKE.</span><i></i><small>PLAY / EXPLORE / RETURN</small></div><div class="mini-cover cover-front"><span>STORIES<br>STAY.</span><i></i><small>A PERSONAL COLLECTION</small></div></div></section>
   <section v-else class="page-heading"><p class="eyebrow">{{ view==='shelf'?'A COLLECTION WITH YOUR FINGERPRINTS':'SOMETHING TO LOOK FORWARD TO' }}</p><h1>{{ view==='shelf'?'Your shelf. Your pace.':'Keep the dates close.' }}</h1><p>{{ view==='shelf'?'Save what catches you. Make room for what stays.':'Release dates from your saved items. Add or edit dates as plans change.' }}</p></section>
   <section class="summary" aria-label="Library summary"><div><strong>{{ counts.all.toString().padStart(2,'0') }}</strong><span>on your shelf</span></div><div><strong>{{ counts.active.toString().padStart(2,'0') }}</strong><span>in progress</span></div><div><strong>{{ counts.finished.toString().padStart(2,'0') }}</strong><span>finished</span></div><div><strong>{{ counts.upcoming.toString().padStart(2,'0') }}</strong><span>upcoming</span></div><p>Less keeping up.<br>More paying attention.</p></section>
   <div class="collection-head"><div><p class="eyebrow">{{ view==='discover'?'A PLACE TO BEGIN':'MADE OF YOUR CHOICES' }}</p><h2>{{ view==='discover'?'Explore the starter shelf':view==='shelf'?'The collection':'Your release calendar' }}</h2></div><button v-if="view==='calendar'" @click="exportCalendar">Export calendar ↗</button><span v-if="view==='discover'" class="sample-label">Historical catalog · 2023</span></div>
   <div class="filters"><label class="search"><span class="sr-only">Search media</span><input v-model="query" type="search" placeholder="A title, creator, or genre…"></label><div class="type-tabs" aria-label="Media type"><button :aria-pressed="type==='all'" @click="type='all'">All</button><button v-for="kind in TYPES" :key="kind" :aria-pressed="type===kind" @click="type=kind">{{ typeLabels[kind] }}</button></div></div>
   <div v-if="view!=='discover'" class="shelf-filters"><label>Status<select v-model="statusFilter"><option value="all">All statuses</option><option v-for="s in STATUSES" :key="s" :value="s">{{ statusLabels[s] }}</option><option value="favorites">Favorites</option></select></label><label v-if="view==='shelf'">Sort<select v-model="sort"><option value="recent">Recently added</option><option value="title">Title A–Z</option><option value="rating">Highest rated</option><option value="release">Release date</option></select></label><span>{{ shelfItems.length }} {{ shelfItems.length===1?'item':'items' }}</span></div>
   <p class="notice" role="status" aria-live="polite">{{ message }}</p>
   <div v-if="view==='discover'" class="card-grid"><article v-for="item in discoverItems" :key="item.id" class="media-card"><button class="cover" :class="'palette-'+item.palette" @click="openItem(item)" :aria-label="'View '+item.title"><span class="cover-type">{{ typeLabels[item.type] }} / {{ item.releaseDate.slice(0,4) }}</span><i class="cover-shape" aria-hidden="true"></i><strong>{{ item.title }}</strong><small>{{ item.genres.join(' · ') }}</small></button><div class="card-meta"><span>{{ typeLabels[item.type] }} <b>·</b> {{ item.creator }}</span><button class="save-button" :class="{saved:!!entryFor(item.id)}" @click="add(item)" :aria-label="(entryFor(item.id)?'Saved ':'Save ')+item.title">{{ entryFor(item.id)?'✓ Saved':'+ Save' }}</button></div><button class="title-button" @click="openItem(item)">{{ item.title }}</button></article></div>
   <div v-else-if="view==='shelf'" class="card-grid"><article v-for="entry in shelfItems" :key="entry.item.id" class="media-card"><button class="cover" :class="'palette-'+entry.item.palette" @click="openItem(entry.item)" :aria-label="'View '+entry.item.title"><span class="cover-type">{{ typeLabels[entry.item.type] }} / {{ entry.item.releaseDate.slice(0,4)||'UNDATED' }}</span><i class="cover-shape" aria-hidden="true"></i><strong>{{ entry.item.title }}</strong><small>{{ statusLabels[entry.status] }}</small><span v-if="entry.favorite" class="cover-favorite" aria-label="Favorite">★</span></button><div class="card-meta"><select :value="entry.status" :aria-label="entry.item.title+' status'" @change="update(entry.item.id,{status:($event.target as HTMLSelectElement).value as Status})"><option v-for="s in STATUSES" :key="s" :value="s">{{ statusLabels[s] }}</option></select><span v-if="entry.rating" class="rating" :aria-label="entry.rating+' out of 5'">{{ '★'.repeat(entry.rating) }}</span></div><button class="title-button" @click="openItem(entry.item)">{{ entry.item.title }}</button><p v-if="entry.notes" class="note-preview">{{ entry.notes }}</p></article></div>
   <div v-else class="calendar"><section v-for="group in calendarGroups" :key="group.name" class="calendar-group"><h3>{{ monthLabel(group.name) }}</h3><button v-for="entry in group.entries" :key="entry.item.id" class="release-row" @click="openItem(entry.item)"><span class="release-date">{{ entry.item.releaseDate?new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(entry.item.releaseDate+'T12:00:00')):'TBA' }}</span><span><strong>{{ entry.item.title }}</strong><small>{{ typeLabels[entry.item.type] }} · {{ statusLabels[entry.status] }}</small></span><span class="release-year">{{ entry.item.releaseDate.slice(0,4) }}</span><span>↗</span></button></section></div>
   <div v-if="(view==='discover'&&!discoverItems.length)||(view!=='discover'&&!shelfItems.length)" class="empty"><span class="empty-mark">▤</span><h2>{{ counts.all||view==='discover'?'Nothing in this view.':'Your taste takes shape here.' }}</h2><p>{{ counts.all||view==='discover'?'Try another search or filter. You can always add a title of your own.':'Save a few titles from Discover, add your own, or try a sample shelf.' }}</p><div><button class="primary" @click="editItem()">+ Add your own</button><button v-if="!counts.all" @click="demoShelf">Try a sample shelf</button><button v-else @click="query='';type='all';statusFilter='all'">Clear filters</button></div></div>
   <p v-if="view==='discover'" class="catalog-note">A small historical catalog from the original MediaMEMO project. These are examples, not personalized recommendations or a live release feed. Add your own films, games, books, series, and music.</p>
  </main><footer><span>By the viewers, for the viewers. <b>MediaMEMO</b></span><span>Your collection stays in this browser. <a href="https://github.com/MichaelSanders08/MediaMEMO">Source ↗</a></span></footer></div>
 </div>
 <dialog ref="detailDialog" class="detail-dialog"><template v-if="selected"><button class="close" aria-label="Close details" @click="detailDialog?.close()">×</button><div class="detail-top"><div class="detail-cover cover" :class="'palette-'+selected.palette"><span class="cover-type">{{ typeLabels[selected.type] }}</span><i class="cover-shape" aria-hidden="true"></i><strong>{{ selected.title }}</strong></div><div><p class="eyebrow">{{ typeLabels[selected.type] }} / {{ selected.releaseDate.slice(0,4)||'UNDATED' }}</p><h2>{{ selected.title }}</h2><p class="creator">{{ selected.creator }}</p><p class="description">{{ selected.description }}</p><p class="small">Release: {{ formatDate(selected.releaseDate) }}</p><div class="genre-list"><span v-for="genre in selected.genres" :key="genre">{{ genre }}</span></div><a v-if="selected.source" :href="selected.source" target="_blank" rel="noreferrer" class="source-link">Source / more about this title ↗</a></div></div>
  <div v-if="selectedEntry" class="detail-library"><div class="row"><label>Where it stands<select :value="selectedEntry.status" @change="update(selected.id,{status:($event.target as HTMLSelectElement).value as Status})"><option v-for="s in STATUSES" :key="s" :value="s">{{ statusLabels[s] }}</option></select></label><label>Your rating<select :value="selectedEntry.rating" @change="update(selected.id,{rating:Number(($event.target as HTMLSelectElement).value)})"><option :value="0">Not rated</option><option v-for="n in 5" :key="n" :value="n">{{ n }} / 5</option></select></label><button class="favorite-button" :aria-pressed="selectedEntry.favorite" @click="update(selected.id,{favorite:!selectedEntry.favorite})">{{ selectedEntry.favorite?'★ Favorited':'☆ Favorite' }}</button></div><label>What stayed with you?<textarea v-model="draftNotes" maxlength="10000" placeholder="A thought, a quote in your own notes, a reason to come back…"></textarea></label><div class="dialog-actions"><button class="primary" @click="update(selected.id,{notes:draftNotes});detailDialog?.close()">Save notes</button><button @click="editItem(selected)">Edit details</button><button class="danger" @click="remove(selected.id)">Remove from shelf</button></div></div><div v-else class="dialog-actions"><button class="primary" @click="add(selected)">+ Save to my shelf</button></div>
 </template></dialog>
 <dialog ref="editDialog" class="edit-dialog"><form @submit.prevent="saveItem"><div class="dialog-heading"><div><p class="eyebrow">MAKE ROOM FOR YOUR OWN FINDS</p><h2>{{ editId?'Refine the details.':'Add something good.' }}</h2></div><button type="button" class="close-inline" aria-label="Close editor" @click="editDialog?.close()">×</button></div><div class="row"><label>Title<input v-model="form.title" maxlength="160" required autofocus></label><label>Type<select v-model="form.type"><option v-for="kind in TYPES" :key="kind" :value="kind">{{ typeLabels[kind] }}</option></select></label></div><div class="row"><label>Creator / artist / studio<input v-model="form.creator" maxlength="160"></label><label>Release date · optional<input v-model="form.releaseDate" type="date"></label></div><label>A little context<textarea v-model="form.description" maxlength="5000" rows="3"></textarea></label><div class="row"><label>Genres · comma separated<input v-model="form.genres" placeholder="Drama, Science fiction"></label><label>Source link · optional<input v-model="form.source" type="url" placeholder="https://" maxlength="1000"></label></div><p class="notice" role="alert">{{ formError }}</p><button class="primary" type="submit">{{ editId?'Save changes':'Add to my shelf' }} ↗</button></form></dialog>
</template>
